version: '3'
services:
  # ref: https://www.xuxueli.com/xxl-job
  # http://localhost:8080/xxl-job-admin ； 默认登录账号 “admin/123456”
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.1.2
    container_name: xxl-job-admin
    restart: always
    environment:
      PARAMS: "--spring.datasource.username=root --spring.datasource.password=root123 --spring.datasource.url=jdbc:mysql://172.19.205.238:3306/xxl_job?Unicode=true&characterEncoding=UTF-8"
    volumes:
      - /data/docker_file/xxl_job_admin/data/applogs:/data/applogs
    ports:
      - "8080:8080"