version: '3'
services:
  mongo:
    image: mongo:4.1.6
    ports:
      - 27017:27017
    restart: always
    volumes:
      - /data/docker_file/mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
  # mongo可视化管理工具，按需安装
  mongo-express:
    links:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 9090:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123