version: '3'
services:
  # ref: https://github.com/nacos-group/nacos-docker
  # ref: https://github.com/alibaba/nacos
  # 运行前需要执行mysql脚本,修改数据库地址，另外可以通过custom.properties自定义nacos
  nacos:
    image: nacos/nacos-server:1.2.1
    container_name: nacos-standalone-mysql
    hostname: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
      - MYSQL_SERVICE_HOST=kancy.top
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root123
      - NACOS_AUTH_ENABLE=true
    volumes:
      - /data/docker_file/naocs/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9555:9555"
    restart: always
