version: '3'
services:
  # ref: https://hub.docker.com/r/wurstmeister/kafka
  zookeeper:
    image: zookeeper:3.4.11
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ~/data/docker_file/zookeeper/data:/data
      - ~/data/docker_file/zookeeper/datalog:/datalog
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
    volumes:
      - ~/data/docker_file/kafka/logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: zookeeper:2181
