version: '3'
services:
  consul:
    image: consul:latest
    container_name: consul
    volumes:
      - /data/docker_file/consul/data:/consul/data
      - /data/docker_file/consul/config:/consul/config
    ports:
      - 8500:8500
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -node=consul_Server1 -bootstrap-expect=1 -ui