# https://www.cnblogs.com/linanjie/p/13932377.html
#https://www.jianshu.com/p/edf57ba6a159
# 初始化密码在./docker-nexus/data/admin.password里面
version: '3'
services:
  nexus:
    image: 'docker.io/sonatype/nexus3'
    container_name: nexus3
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '8081:8081'
    volumes:
      - '/data/nexus-data:/nexus-data' # sudo chmod -R 777 /data/nexus-data
