global:
  smtp_smarthost: 'smtp.qq.com:25'　　#163服务器
  smtp_from: '793272861@qq.com'　　　　　　　　#发邮件的邮箱
  smtp_auth_username: '793272861@qq.com'　　#发邮件的邮箱用户名，也就是你的邮箱
  smtp_auth_password: 'hlmefmhbmgopbehi'　　　　　　　　#发邮件的邮箱密码
  smtp_require_tls: false　　　　　　　　#不进行tls验证
 
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
- name: 'live-monitoring'
  email_configs:
  - to: '793272861@qq.com'　　　　　　　　#收邮件的邮箱