
version: '3'
services:
    rabbitmq:
       image: rabbitmq:management
       hostname: myrabbitmq
       container_name: rabbitmq
       restart: always
       environment:
         - RABBITMQ_DEFAULT_VHOST=myrabbitmq-vhost
         - RABBITMQ_DEFAULT_USER=root
         - RABBITMQ_DEFAULT_PASS=root
       volumes:
         - "./data:/var/lib/rabbitmq"
         - "./log:/var/log/rabbitmq/log"
       ports:
         - "15672:15672"
         - "4369:4369"
         - "5672:5672"
         - "25672:25672"
